### ISSUE TITLE
failed with unknown libva

### ISSUE THREAD

**Issue by Slender1808** [flathub/electron-sample-app#6]
I tried to run sample when I tried to open electron-sample-app-1.0.1.AppImage this error happened, I'm using fedora 35 with nvidia gpu

libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[866834:1209/233428.951966:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.

**Comment by cpba** [comment]
Is it possible that you might be posting in the wrong place?

This is the sample repo for the flatpak electron tutorial:

https://docs.flatpak.org/en/latest/electron.html

Otherwise it's entirely useless and has nothing to do with appimage, It exists purely to demonstrate how to build an electron app using `flatpak-builder`.
